import js from "@eslint/js";
import tseslint from "typescript-eslint";
import globals from "globals";

export default tseslint.config(
  {
    ignores: [
      "**/dist/**",
      "**/node_modules/**",
      // Regenerated by vitest globalSetup — not checked in.
      "packages/channel-harness/__tests__/generated-sdk/**",
      "packages/channel-harness/__tests__/__generated__/**",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        ...globals.node,
      },
    },
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      // AST parsers and JSON-shape interfaces legitimately use `any` /
      // unknown-shaped records. The strict checks against our own types in
      // `src/ast/` are enforced by tsc already.
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
);
