import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { cleanStaleFiles } from "../../src/utils/codegen.js";
import { writeElixirFiles } from "../../src/backends/elixir/index.js";

describe("generated-file cleanup", () => {
  it("removes nested stale files without following directory symlinks", () => {
    const base = mkdtempSync(join(tmpdir(), "archastro-cleanup-"));
    const generated = join(base, "generated");
    const outside = join(base, "outside");
    const marker = "# This file is auto-generated by @archastro/sdk-generator. Do not edit.\n";

    try {
      mkdirSync(join(generated, "nested"), { recursive: true });
      mkdirSync(outside, { recursive: true });
      const nested = join(generated, "nested", "stale.ex");
      const protectedFile = join(outside, "protected.ex");
      writeFileSync(nested, marker);
      writeFileSync(protectedFile, marker);
      symlinkSync(outside, join(generated, "linked-outside"), "dir");

      cleanStaleFiles({}, [generated], [".ex"], true);

      expect(existsSync(nested)).toBe(false);
      expect(existsSync(protectedFile)).toBe(true);
    } finally {
      rmSync(base, { recursive: true, force: true });
    }
  });

  it("refuses to overwrite a symlinked generated destination", () => {
    const base = mkdtempSync(join(tmpdir(), "archastro-write-"));
    const generated = join(base, "generated");
    const outside = join(base, "outside.ex");
    const destination = join(generated, "auth.ex");
    const marker = "# This file is auto-generated by @archastro/sdk-generator. Do not edit.\n";

    try {
      mkdirSync(generated, { recursive: true });
      writeFileSync(outside, "protected");
      symlinkSync(outside, destination, "file");

      expect(() => writeElixirFiles({ [destination]: marker }, [generated], true))
        .toThrow(/through symlink/);
      expect(readFileSync(outside, "utf8")).toBe("protected");
    } finally {
      rmSync(base, { recursive: true, force: true });
    }
  });

  it("refuses cleanup through a symlinked generated-directory ancestor", () => {
    const base = mkdtempSync(join(tmpdir(), "archastro-codegen-"));
    try {
      const outside = join(base, "outside");
      const generated = join(outside, "generated");
      mkdirSync(generated, { recursive: true });
      const protectedFile = join(generated, "protected.ex");
      writeFileSync(protectedFile, "protected", "utf8");

      const linkedRoot = join(base, "linked-root");
      symlinkSync(outside, linkedRoot, "dir");

      expect(() => writeElixirFiles({}, [join(linkedRoot, "generated")], true))
        .toThrow(/through symlink/);
      expect(readFileSync(protectedFile, "utf8")).toBe("protected");
    } finally {
      rmSync(base, { recursive: true, force: true });
    }
  });
});
