/**
 * Code generation utilities — indentation, import tracking, file writing.
 */

import { createHash } from "node:crypto";
import { readdirSync, readFileSync, unlinkSync, statSync } from "node:fs";
import { join } from "node:path";

export class CodeBuilder {
  private lines: string[] = [];
  private indentLevel = 0;
  private indentStr: string;

  constructor(indentStr = "  ") {
    this.indentStr = indentStr;
  }

  indent(): this {
    this.indentLevel++;
    return this;
  }

  dedent(): this {
    this.indentLevel = Math.max(0, this.indentLevel - 1);
    return this;
  }

  line(text = ""): this {
    if (text === "") {
      this.lines.push("");
    } else {
      this.lines.push(this.indentStr.repeat(this.indentLevel) + text);
    }
    return this;
  }

  block(header: string, fn: () => void): this {
    this.line(header + " {");
    this.indent();
    fn();
    this.dedent();
    this.line("}");
    return this;
  }

  /** Python-style block: header with colon, indented body, no closing brace. */
  pyBlock(header: string, fn: () => void): this {
    this.line(header + ":");
    this.indent();
    fn();
    this.dedent();
    return this;
  }

  toString(): string {
    return this.lines.join("\n") + "\n";
  }
}

/**
 * Tracks imports and emits a sorted import block.
 */
export class ImportTracker {
  private imports = new Map<string, Set<string>>();
  private typeImports = new Map<string, Set<string>>();

  add(module: string, ...names: string[]): this {
    const existing = this.imports.get(module) ?? new Set();
    for (const name of names) existing.add(name);
    this.imports.set(module, existing);
    return this;
  }

  addType(module: string, ...names: string[]): this {
    const existing = this.typeImports.get(module) ?? new Set();
    for (const name of names) existing.add(name);
    this.typeImports.set(module, existing);
    return this;
  }

  emit(): string {
    const lines: string[] = [];

    for (const [module, names] of sortedEntries(this.imports)) {
      const sorted = [...names].sort();
      lines.push(`import { ${sorted.join(", ")} } from "${module}";`);
    }

    for (const [module, names] of sortedEntries(this.typeImports)) {
      const sorted = [...names].sort();
      lines.push(`import type { ${sorted.join(", ")} } from "${module}";`);
    }

    return lines.length > 0 ? lines.join("\n") + "\n" : "";
  }
}

function sortedEntries<V>(map: Map<string, V>): [string, V][] {
  return [...map.entries()].sort(([a], [b]) => a.localeCompare(b));
}

/**
 * Header comment for generated files (placeholder — hash added later).
 */
export function generatedHeader(): string {
  return `// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.\n// This file is auto-generated by @archastro/sdk-generator. Do not edit.\n`;
}

/**
 * Emit a Python import line, wrapping to multi-line if it exceeds the line length limit.
 */
export function emitPythonImportLine(cb: CodeBuilder, mod: string, names: string[], lineLength = 100): void {
  const oneLiner = `from ${mod} import ${names.join(", ")}`;
  if (oneLiner.length <= lineLength) {
    cb.line(oneLiner);
  } else {
    cb.line(`from ${mod} import (`);
    for (const name of names) {
      cb.line(`    ${name},`);
    }
    cb.line(")");
  }
}

export function generatedHeaderPython(): string {
  return `# Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.\n# This file is auto-generated by @archastro/sdk-generator. Do not edit.\n`;
}

/**
 * Add a content hash to the generated file header.
 * The hash covers the file content AFTER the header line so it's stable.
 */
export function addContentHash(content: string, commentPrefix = "//"): string {
  const hash = createHash("sha256").update(content).digest("hex").slice(0, 12);
  const hashLine = `${commentPrefix} Content hash: ${hash}`;

  // Find the auto-generated marker line and insert hash after it
  const marker = "This file is auto-generated by @archastro/sdk-generator. Do not edit.";
  const markerPatterns = [
    `// ${marker}`,
    `# // ${marker}`,
    `# ${marker}`,
  ];

  for (const pattern of markerPatterns) {
    if (content.includes(pattern)) {
      return content.replace(pattern, `${pattern}\n${hashLine}`);
    }
  }

  // Fallback: prepend copyright + header + hash
  const copyright = `${commentPrefix} Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.`;
  const headerLine = `${commentPrefix} ${marker}`;
  return `${copyright}\n${headerLine}\n${hashLine}\n\n${content}`;
}

const GENERATED_MARKER = "This file is auto-generated by @archastro/sdk-generator. Do not edit.";

/**
 * Delete auto-generated files in `dirs` that are not in the new `files` map.
 * Only deletes files containing the auto-generated marker header.
 */
export function cleanStaleFiles(
  files: Record<string, string>,
  dirs: string[],
  extensions: string[]
): void {
  const newPaths = new Set(Object.keys(files));
  const extSet = new Set(extensions);

  for (const dir of dirs) {
    let entries: string[];
    try {
      entries = readdirSync(dir);
    } catch {
      continue; // dir doesn't exist yet
    }

    for (const entry of entries) {
      const fullPath = join(dir, entry);
      try {
        if (!statSync(fullPath).isFile()) continue;
      } catch {
        continue;
      }
      const ext = entry.substring(entry.lastIndexOf("."));
      if (!extSet.has(ext)) continue;
      if (newPaths.has(fullPath)) continue;

      // Only delete files we previously generated
      try {
        const head = readFileSync(fullPath, "utf-8").slice(0, 200);
        if (head.includes(GENERATED_MARKER)) {
          unlinkSync(fullPath);
        }
      } catch {
        // skip unreadable files
      }
    }
  }
}
