import { lstatSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, join, parse, relative, resolve, sep } from "node:path";
import type {
  ChannelDef,
  ChannelJoinDef,
  ChannelMessageDef,
  ChannelPushDef,
  FieldDef,
  OperationDef,
  ParamDef,
  ResourceDef,
  SchemaDef,
  SdkSpec,
  StreamingEvent,
  TypeRef,
  VersionedResourceSet,
} from "../../ast/types.js";
import { addContentHash, cleanStaleFiles, CodeBuilder } from "../../utils/codegen.js";
import { pascalCase } from "../../utils/naming.js";
import { hoistInlineObjects } from "../python/inline-object-hoist.js";
import {
  exFieldName,
  exFunctionName,
  exModuleSegment,
  exString,
  uniqueExFieldNames,
  uniqueExFileStems,
  uniqueExFunctionNames,
  uniqueExModuleSegments,
} from "./identifiers.js";

export const ELIXIR_GENERATED_DIR = "lib/archastro/generated";

export interface ElixirBackendOptions { outDir: string }
export type GeneratedFiles = Record<string, string>;

function header(): string {
  return "# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.\n" +
    "# This file is auto-generated by @archastro/sdk-generator. Do not edit.\n";
}

export function generateElixir(spec: SdkSpec, options: ElixirBackendOptions): GeneratedFiles {
  spec = prepareElixirSpec(spec);
  const files: GeneratedFiles = {};
  const root = join(options.outDir, ELIXIR_GENERATED_DIR);

  const schemaGroups = Object.entries(spec.schemaGroups);
  const schemaGroupStems = uniqueExFileStems(schemaGroups.map(([group]) => group));
  schemaGroups.forEach(([, schemas], index) => {
    files[join(root, "types", `${schemaGroupStems[index]!}.ex`)] = emitSchemaFile(schemas);
  });

  const versionStems = uniqueExFileStems(spec.versions.map((version) => version.version));
  spec.versions.forEach((version, versionIndex) => {
    const resourceStems = uniqueExFileStems(version.resources.map((resource) => resource.name));
    version.resources.forEach((resource, resourceIndex) => {
      files[join(root, versionStems[versionIndex]!, `${resourceStems[resourceIndex]!}.ex`)] =
        emitResourceTree(version, resource);
    });
  });

  const channelFileStems = uniqueExFileStems(spec.channels.map((channel) => channel.name));
  spec.channels.forEach((channel, index) => {
    files[join(root, "channels", `${channelFileStems[index]!}.ex`)] = emitChannel(channel);
  });

  files[join(root, "auth.ex")] = emitAuth(spec);
  files[join(root, "client.ex")] = emitClient(spec);
  return files;
}

export function prepareElixirSpec(spec: SdkSpec): SdkSpec {
  const cloned: SdkSpec = structuredClone(spec);
  const schemaNames = uniqueExModuleSegments(cloned.schemas.map((schema) => schema.name));
  const schemaMap = new Map(cloned.schemas.map((schema, index) => [schema.name, schemaNames[index]!]));

  const rewriteType = (type: TypeRef): void => {
    switch (type.kind) {
      case "ref":
        type.schema = schemaMap.get(type.schema) ?? type.schema;
        break;
      case "array": rewriteType(type.items); break;
      case "object": rewriteFields(type.fields); break;
      case "union":
        if (type.discriminator && !type.discriminator.mapping) {
          type.discriminator.mapping = Object.fromEntries(
            type.variants
              .filter((variant): variant is Extract<TypeRef, { kind: "ref" }> => variant.kind === "ref")
              .map((variant) => [variant.schema, schemaMap.get(variant.schema) ?? variant.schema])
          );
        }
        type.variants.forEach(rewriteType);
        if (type.discriminator?.mapping) {
          type.discriminator.mapping = Object.fromEntries(
            Object.entries(type.discriminator.mapping).map(([tag, name]) => [tag, schemaMap.get(name) ?? name])
          );
        }
        break;
      case "nullable":
      case "optional": rewriteType(type.inner); break;
      case "map":
        rewriteType(type.keyType);
        rewriteType(type.valueType);
        break;
    }
  };
  const rewriteFields = (fields: FieldDef[]): void => fields.forEach((field) => rewriteType(field.type));
  const rewriteOperation = (op: OperationDef): void => {
    op.pathParams.forEach((param) => rewriteType(param.type));
    op.queryParams.forEach((param) => rewriteType(param.type));
    if (op.body?.fields) rewriteFields(op.body.fields);
    if (op.body?.schema) op.body.schema = schemaMap.get(op.body.schema) ?? op.body.schema;
    rewriteType(op.returnType);
    if (op.streaming) {
      const eventTypes = uniqueExModuleSegments(op.streaming.events.map((event) => event.event));
      op.streaming.events.forEach((event, index) => {
        event.sdkTypeName = eventTypes[index]!;
        rewriteType(event.dataType);
      });
    }
  };
  const rewriteResources = (resources: ResourceDef[]): void => {
    const normalized = resources.map((resource) => exModuleSegment(resource.name));
    if (new Set(normalized).size !== normalized.length) {
      const names = uniqueExModuleSegments(resources.map((resource) => resource.name));
      resources.forEach((resource, index) => { resource.name = names[index]!; });
    }
    for (const resource of resources) {
      rewriteFields(resource.scopeParams);
      const methodNames = uniqueExFunctionNames(resource.operations.map((op) => op.sdkName ?? op.name));
      resource.operations.forEach((op, index) => {
        if (methodNames[index] !== exFunctionName(op.sdkName ?? op.name)) op.sdkName = methodNames[index];
        rewriteOperation(op);
      });
      rewriteResources(resource.children);
    }
  };

  cloned.schemas.forEach((schema, index) => {
    schema.name = schemaNames[index]!;
    rewriteFields(schema.fields);
    if (schema.unionType) rewriteType(schema.unionType);
  });
  for (const schemas of Object.values(cloned.schemaGroups)) {
    for (const schema of schemas) {
      schema.name = schemaMap.get(schema.name) ?? schema.name;
      rewriteFields(schema.fields);
      if (schema.unionType) rewriteType(schema.unionType);
    }
  }
  const versionModules = uniqueExModuleSegments(cloned.versions.map((version) => version.version));
  cloned.versions.forEach((version, index) => { version.sdkName = versionModules[index]!; });
  cloned.versions.forEach((version) => rewriteResources(version.resources));
  cloned.resources = cloned.versions.find((version) => version.version === cloned.defaultVersion)?.resources ?? cloned.resources;
  const authNames = uniqueExFunctionNames(
    cloned.authOperations.map(elixirAuthMethodName)
  );
  cloned.authOperations.forEach((operation, index) => {
    operation.sdkName = authNames[index]!;
    rewriteOperation(operation);
  });

  const operations = [
    ...cloned.authOperations,
    ...cloned.versions.flatMap((version) =>
      flattenResourcesList(version.resources).flatMap((resource) => resource.operations)
    ),
  ];
  const operationSegments = operations.map((op) => exModuleSegment(op.operationId));
  if (new Set(operationSegments).size !== operationSegments.length) {
    const names = uniqueExModuleSegments(operations.map((op) => op.operationId));
    operations.forEach((op, index) => { op.operationId = names[index]!; });
  }

  const channelClasses = uniqueExModuleSegments(
    cloned.channels.map((channel) => channel.className.replace(/Channel$/, ""))
  );
  cloned.channels.forEach((channel, index) => {
    channel.sdkName = channelClasses[index]!;
    const memberTypes = uniqueExModuleSegments([
      ...channel.joins.map((joinDef, joinIndex) => joinDef.name ?? `join_${joinIndex + 1}`),
      ...channel.messages.map((message) => message.event),
      ...channel.pushes.map((push) => push.event),
    ]);
    channel.joins.forEach((joinDef, joinIndex) => {
      joinDef.sdkTypeName = memberTypes[joinIndex]!;
      joinDef.params.forEach((param) => rewriteType(param.type));
      rewriteType(joinDef.returnType);
    });
    channel.messages.forEach((message, messageIndex) => {
      message.sdkTypeName = memberTypes[channel.joins.length + messageIndex]!;
      message.params.forEach((param) => rewriteType(param.type));
      rewriteType(message.returnType);
    });
    channel.pushes.forEach((push, pushIndex) => {
      push.sdkTypeName = memberTypes[channel.joins.length + channel.messages.length + pushIndex]!;
      rewriteType(push.payloadType);
    });
  });
  return cloned;
}

function flattenResourcesList(resources: ResourceDef[]): ResourceDef[] {
  return resources.flatMap((resource) => [resource, ...flattenResourcesList(resource.children)]);
}

export function writeElixirFiles(
  files: GeneratedFiles,
  cleanDirs: string[],
  recursive = false
): void {
  cleanDirs.forEach(assertNoSymlinkAncestors);
  cleanStaleFiles(files, cleanDirs, [".ex", ".exs"], recursive);
  for (const [path, content] of Object.entries(files)) {
    assertSafeElixirWritePath(path, cleanDirs);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, addContentHash(content, "#"), "utf8");
  }
}

function assertNoSymlinkAncestors(path: string): void {
  const target = resolve(path);
  const root = parse(target).root;
  const segments = relative(root, target).split(sep).filter(Boolean);
  let current = root;

  for (const segment of segments) {
    current = join(current, segment);
    try {
      if (lstatSync(current).isSymbolicLink()) {
        throw new Error(`Refusing to access generated Elixir directory through symlink: ${current}`);
      }
    } catch (error) {
      if (error instanceof Error && error.message.startsWith("Refusing")) throw error;
      // Missing descendants are safe to create after all existing ancestors pass.
    }
  }
}

function assertSafeElixirWritePath(path: string, roots: ReadonlyArray<string>): void {
  const target = resolve(path);
  const root = roots
    .map((candidate) => resolve(candidate))
    .find((candidate) => {
      const rel = relative(candidate, target);
      return rel === "" || (!rel.startsWith(`..${sep}`) && rel !== ".." && !isAbsolute(rel));
    });
  if (!root) throw new Error(`Refusing to write generated Elixir file outside configured roots: ${path}`);

  const segments = relative(root, target).split(sep).filter(Boolean);
  let current = root;
  for (const segment of ["", ...segments]) {
    if (segment) current = join(current, segment);
    try {
      if (lstatSync(current).isSymbolicLink()) {
        throw new Error(`Refusing to write generated Elixir file through symlink: ${current}`);
      }
    } catch (error) {
      if (error instanceof Error && error.message.startsWith("Refusing")) throw error;
      // Missing path components are created after all existing ancestors pass.
    }
  }
}

function beginFile(cb: CodeBuilder): void {
  header().trimEnd().split("\n").forEach((line) => cb.line(line));
  cb.line();
}

function emitSchemaFile(schemas: SchemaDef[]): string {
  const cb = new CodeBuilder("  ");
  beginFile(cb);
  for (const schema of schemas) {
    if (schema.unionType) emitUnionSchema(cb, schema);
    else emitInlineStructs(cb, schema.name, schema.fields, schema.description);
    if (schema.unionType) cb.line();
  }
  return cb.toString();
}

function emitUnionSchema(cb: CodeBuilder, schema: SchemaDef): void {
  const hoist = hoistInlineObjects(
    [{ name: "variant", type: schema.unionType!, required: true }],
    `${schema.name}.Nested.`,
    "typeddict",
    { hoistUnions: true }
  );
  for (const child of hoist.hoisted) {
    emitStruct(cb, typeModule(child.name), child.fields, child.description);
    cb.line();
  }
  const moduleName = `ArchAstro.Types.${exModuleSegment(schema.name)}`;
  const union = hoist.fields[0]!.type;
  cb.line(`defmodule ${moduleName} do`);
  cb.indent();
  cb.line(`@moduledoc ${heredoc(schema.description ?? `${schema.name} API union.`)}`);
  cb.line(`@type t :: ${typeSpec(union)}`);
  cb.line(`@descriptor ${descriptor(union)}`);
  cb.line("@spec from_map(ArchAstro.JSON.t()) :: t()");
  cb.line("def from_map(value), do: ArchAstro.Codec.decode(value, @descriptor)");
  cb.line("@spec to_map(t()) :: ArchAstro.JSON.t()");
  cb.line("def to_map(value), do: ArchAstro.Codec.encode(value)");
  cb.line("@spec matches?(ArchAstro.JSON.t()) :: boolean()");
  cb.line("def matches?(value), do: ArchAstro.Codec.matches?(value, @descriptor)");
  cb.dedent();
  cb.line("end");
}

function emitStruct(
  cb: CodeBuilder,
  moduleName: string,
  fields: ReadonlyArray<FieldDef>,
  description?: string,
  wireNames: ReadonlyMap<string, string> = new Map(),
  redactInspect = false
): void {
  cb.line(`defmodule ${moduleName} do`);
  cb.indent();
  cb.line(`@moduledoc ${heredoc(description ?? `${moduleName.split(".").at(-1)} API model.`)}`);
  const fieldNames = uniqueExFieldNames(fields.map((field) => field.name));
  const required = fields
    .map((field, index) => ({ field, name: fieldNames[index]! }))
    .filter(({ field }) => field.required)
    .map(({ name }) => `:${name}`);
  if (required.length > 0) cb.line(`@enforce_keys [${required.join(", ")}]`);
  const members = fields.map((field, index) => {
    const name = fieldNames[index]!;
    return field.required ? `${name}: nil` : `${name}: :__archastro_unset__`;
  });
  cb.line(`defstruct [${members.join(", ")}]`);
  cb.line();
  cb.line("@type t :: %__MODULE__{");
  cb.indent();
  fields.forEach((field, index) => {
    const suffix = index === fields.length - 1 ? "" : ",";
    const optional = field.required ? "" : " | ArchAstro.Unset.t()";
    cb.line(`${fieldNames[index]!}: ${typeSpec(field.type)}${optional}${suffix}`);
  });
  cb.dedent();
  cb.line("}");
  cb.line();
  const descriptors = fields.map((field, index) =>
    `${fieldNames[index]!}: {${exString(wireNames.get(field.name) ?? field.wireName ?? field.name)}, ${fieldDescriptor(field)}}`
  );
  cb.line(`@fields [${descriptors.join(", ")}]`);
  cb.line("@spec from_map(ArchAstro.JSON.object()) :: t()");
  cb.line("def from_map(data), do: ArchAstro.Codec.struct_from_map(__MODULE__, data, @fields)");
  cb.line("@spec to_map(t()) :: ArchAstro.JSON.object()");
  cb.line("def to_map(value), do: ArchAstro.Codec.struct_to_map(value, @fields)");
  cb.line("@spec matches?(ArchAstro.JSON.t()) :: boolean()");
  cb.line("def matches?(value), do: ArchAstro.Codec.matches?(value, {:object, Keyword.values(@fields)})");
  cb.dedent();
  cb.line("end");
  if (redactInspect || fields.some((field) => Boolean(field.sdkRole))) {
    cb.line();
    cb.line(`defimpl Inspect, for: ${moduleName} do`);
    cb.indent();
    cb.line(`def inspect(_value, _opts), do: ${exString(`#${moduleName}<[REDACTED]>`)}`);
    cb.dedent();
    cb.line("end");
  }
}

function emitInlineStructs(
  cb: CodeBuilder,
  rootName: string,
  fields: ReadonlyArray<FieldDef>,
  description?: string,
  wireNames: ReadonlyMap<string, string> = new Map(),
  redactInspect = false
): void {
  const hoist = hoistInlineObjects(
    fields,
    `${rootName}.Nested.`,
    "typeddict",
    { hoistUnions: true }
  );
  for (const child of hoist.hoisted) {
    emitStruct(cb, typeModule(child.name), child.fields, child.description, new Map(), redactInspect);
    cb.line();
  }
  emitStruct(cb, typeModule(rootName), hoist.fields, description, wireNames, redactInspect);
  cb.line();
}

function emitNestedTypeStructs(
  cb: CodeBuilder,
  type: TypeRef,
  rootName: string,
  description?: string
): TypeRef {
  const hoist = hoistInlineObjects(
    [{ name: "value", type, required: true }],
    `${rootName}.Nested.`,
    "typeddict",
    { hoistUnions: true }
  );
  for (const child of hoist.hoisted) {
    emitStruct(cb, typeModule(child.name), child.fields, description ?? child.description);
    cb.line();
  }
  return hoist.fields[0]!.type;
}

export function typeModule(name: string): string {
  return `ArchAstro.Types.${name.split(".").map(exModuleSegment).join(".")}`;
}

function operationTypeRoot(op: OperationDef, suffix: string): string {
  return `Operations.${pascalCase(op.operationId)}.${suffix}`;
}

export function inlineBodyName(op: OperationDef): string {
  return operationTypeRoot(op, "Input");
}

function inlineResponseName(op: OperationDef): string {
  return operationTypeRoot(op, "Response");
}

export function queryParamsName(op: OperationDef): string {
  return operationTypeRoot(op, "Params");
}

function queryFields(op: OperationDef): FieldDef[] {
  return op.queryParams.map((param) => ({
    name: param.name,
    type: param.type,
    required: param.required,
    default: param.default,
    description: param.description,
  }));
}

function paramWireNames(params: ReadonlyArray<ParamDef>): Map<string, string> {
  return new Map(params.map((param) => [param.name, param.wireName ?? param.name]));
}

function emitResourceTree(version: VersionedResourceSet, root: ResourceDef): string {
  const cb = new CodeBuilder("  ");
  beginFile(cb);
  for (const resource of flattenResources(root)) {
    for (const op of resource.operations) {
      if (op.body?.fields) emitInlineStructs(cb, inlineBodyName(op), op.body.fields, op.summary);
      if (op.queryParams.length > 0) {
        emitInlineStructs(
          cb,
          queryParamsName(op),
          queryFields(op),
          `${op.summary ?? op.name} query parameters.`,
          paramWireNames(op.queryParams)
        );
      }
      if (!op.rawResponse && op.returnType.kind === "object" && op.returnType.fields.length > 0) {
        emitInlineStructs(cb, inlineResponseName(op), op.returnType.fields, op.returnDescription ?? op.summary);
      } else if (!op.rawResponse) {
        op.returnType = emitNestedTypeStructs(
          cb,
          op.returnType,
          inlineResponseName(op),
          op.returnDescription ?? op.summary
        );
      }
      if (op.streaming) emitStreamingTypes(cb, op);
    }
  }
  const initial = elixirResourceChain(version, [root]);
  walkResource(cb, version, root, initial, [root]);
  return cb.toString();
}

function flattenResources(resource: ResourceDef): ResourceDef[] {
  return [resource, ...resource.children.flatMap(flattenResources)];
}

function walkResource(
  cb: CodeBuilder,
  version: VersionedResourceSet,
  resource: ResourceDef,
  chain: string[],
  ancestry: ResourceDef[]
): void {
  if (resource.operations.length > 0) {
    const moduleName = ["ArchAstro", exModuleSegment(version.sdkName ?? version.version), ...chain.map(exModuleSegment)].join(".");
    cb.line(`defmodule ${moduleName} do`);
    cb.indent();
    cb.line(`@moduledoc ${heredoc(resource.description ?? `${resource.className.replace(/Resource$/, "")} API resource.`)}`);
    for (const op of resource.operations) {
      cb.line();
      emitOperation(cb, op, resource);
    }
    cb.dedent();
    cb.line("end");
    cb.line();
  }

  for (const child of resource.children) {
    const childChain = elixirResourceChain(version, [...ancestry, child]);
    walkResource(cb, version, child, childChain, [...ancestry, child]);
  }
}

export function elixirResourceChain(version: VersionedResourceSet, resources: ResourceDef[]): string[] {
  const names = resources.map((resource) => resource.name);
  while (names[0] === "api" || names[0] === version.version) names.shift();
  return names;
}

function emitOperation(cb: CodeBuilder, op: OperationDef, resource: ResourceDef): void {
  const name = exFunctionName(op.sdkName ?? op.name);
  const args: string[] = ["client"];
  const argSpecs: string[] = ["ArchAstro.Client.t()"];
  const pathParams = [...resource.scopeParams, ...op.pathParams];
  const pathArgNames = uniqueExFunctionNames(
    pathParams.map((param) => param.name),
    ["client", "input", "params", "path"]
  );
  resource.scopeParams.forEach((p, index) => {
    args.push(pathArgNames[index]!);
    argSpecs.push(typeSpec(p.type));
  });
  op.pathParams.forEach((p, index) => {
    args.push(pathArgNames[resource.scopeParams.length + index]!);
    argSpecs.push(typeSpec(p.type));
  });
  if (op.body) {
    args.push("input");
    argSpecs.push(bodyTypeSpec(op));
  }
  if (op.queryParams.length > 0) {
    const paramsType = `${typeModule(queryParamsName(op))}.t()`;
    const defaultValue = op.queryParams.some((param) => param.required)
      ? "params"
      : `params \\\\ %${typeModule(queryParamsName(op))}{}`;
    args.push(defaultValue);
    argSpecs.push(paramsType);
  }
  const doc = [op.summary, op.description, op.returnDescription].filter(Boolean).join("\n\n");
  cb.line(`@doc ${heredoc(doc || `${op.method} ${op.path}`)}`);
  if (op.deprecated) cb.line('@deprecated "Deprecated by the OpenAPI contract"');
  cb.line(`@spec ${name}(${argSpecs.join(", ")}) :: ${operationResultSpec(op)}`);
  cb.line(`def ${name}(${args.join(", ")}) do`);
  cb.indent();
  cb.line(`path = ${pathExpression(op.path, pathParams, pathArgNames)}`);
  const options: string[] = [];
  if (op.queryParams.length > 0) options.push("query: params");
  if (op.body) options.push("body: input");
  if (op.streaming) {
    options.push(`decode_event: &${typeModule(streamEventName(op))}.decode/1`);
    cb.line(`ArchAstro.SSE.stream(client, :${op.method.toLowerCase()}, path, [${options.join(", ")}])`);
  } else {
    if (op.rawResponse) options.push("raw: true");
    else options.push(`decode: ${operationDescriptor(op)}`);
    cb.line(`ArchAstro.HTTP.request(client, :${op.method.toLowerCase()}, path, [${options.join(", ")}])`);
  }
  cb.dedent();
  cb.line("end");
}

function bodyTypeSpec(op: OperationDef): string {
  if (op.body?.fields) return `${typeModule(inlineBodyName(op))}.t()`;
  if (op.body?.schema && op.body.schema !== "inline") return `${typeModule(op.body.schema)}.t()`;
  return "ArchAstro.JSON.object()";
}

function operationResultSpec(op: OperationDef): string {
  if (op.streaming) return `ArchAstro.SSE.Stream.t(${typeModule(streamEventName(op))}.t())`;
  const success = op.rawResponse ? "Req.Response.t()" : operationTypeSpec(op);
  return `{:ok, ${success}} | {:error, ArchAstro.Error.reason()}`;
}

function streamEventName(op: OperationDef): string {
  return operationTypeRoot(op, "StreamEvent");
}

function streamEventDataName(op: OperationDef, event: StreamingEvent): string {
  return operationTypeRoot(op, `StreamEvents.${event.sdkTypeName ?? pascalCase(event.event)}Data`);
}

function emitStreamingTypes(cb: CodeBuilder, op: OperationDef): void {
  const events = op.streaming?.events ?? [];
  for (const event of events) {
    if (event.dataType.kind === "object" && event.dataType.fields.length > 0) {
      emitInlineStructs(
        cb,
        streamEventDataName(op, event),
        event.dataType.fields,
        `${event.event} server-sent event payload.`
      );
    } else {
      event.dataType = emitNestedTypeStructs(
        cb,
        event.dataType,
        streamEventDataName(op, event),
        `${event.event} server-sent event payload.`
      );
    }
  }

  const moduleName = typeModule(streamEventName(op));
  cb.line(`defmodule ${moduleName} do`);
  cb.indent();
  cb.line(`@moduledoc ${heredoc(`${op.summary ?? op.name} server-sent events.`)}`);
  const dataTypes = events.length > 0
    ? `${events.map((event) => streamEventDataTypeSpec(op, event)).join(" | ")} | ArchAstro.JSON.t()`
    : "ArchAstro.JSON.t()";
  cb.line(`@type t :: %ArchAstro.SSE.Event{data: ${dataTypes}}`);
  cb.line("@spec decode(ArchAstro.SSE.Event.t()) :: t()");
  if (events.length === 0) {
    cb.line("def decode(event), do: event");
  } else {
    for (const event of events) {
      const eventName = exString(event.event);
      const eventDescriptor = streamEventDataDescriptor(op, event);
      cb.line(`def decode(%ArchAstro.SSE.Event{event: ${eventName}} = value),`);
      cb.indent();
      cb.line(`do: %ArchAstro.SSE.Event{value | data: ArchAstro.Codec.decode(value.data, ${eventDescriptor})}`);
      cb.dedent();
    }
    cb.line("def decode(event), do: event");
  }
  cb.dedent();
  cb.line("end");
  cb.line();
}

function streamEventDataTypeSpec(op: OperationDef, event: StreamingEvent): string {
  return event.dataType.kind === "object" && event.dataType.fields.length > 0
    ? `${typeModule(streamEventDataName(op, event))}.t()`
    : typeSpec(event.dataType);
}

function streamEventDataDescriptor(op: OperationDef, event: StreamingEvent): string {
  return event.dataType.kind === "object" && event.dataType.fields.length > 0
    ? `{:ref, ${typeModule(streamEventDataName(op, event))}}`
    : descriptor(event.dataType);
}

function operationTypeSpec(op: OperationDef): string {
  if (op.returnType.kind === "object" && op.returnType.fields.length > 0) {
    return `${typeModule(inlineResponseName(op))}.t()`;
  }
  return typeSpec(op.returnType);
}

function operationDescriptor(op: OperationDef): string {
  if (op.returnType.kind === "object" && op.returnType.fields.length > 0) {
    return `{:ref, ${typeModule(inlineResponseName(op))}}`;
  }
  return descriptor(op.returnType);
}

function pathExpression(path: string, params: ParamDef[], localNames: string[]): string {
  const replacements: Array<{ patterns: string[]; expression: string }> = [];
  for (let index = 0; index < params.length; index++) {
    const param = params[index]!;
    const local = localNames[index]!;
    const wire = param.wireName ?? param.name;
    replacements.push({
      patterns: [...new Set([`{${wire}}`, `{${param.name}}`])],
      expression: `ArchAstro.Path.encode(${local})`,
    });
  }
  return interpolatedString(path, replacements);
}

function emitAuth(spec: SdkSpec): string {
  const cb = new CodeBuilder("  ");
  beginFile(cb);
  for (const op of spec.authOperations ?? []) {
    const fields = authInputFields(op, spec.schemas);
    if (fields.length > 0) {
      emitInlineStructs(cb, authInputName(op), fields, op.summary, authWireNames(op, spec.schemas), true);
    }
    if (!op.rawResponse && op.returnType.kind === "object" && op.returnType.fields.length > 0) {
      emitInlineStructs(cb, inlineResponseName(op), op.returnType.fields, op.returnDescription ?? op.summary);
    } else if (!op.rawResponse) {
      op.returnType = emitNestedTypeStructs(
        cb,
        op.returnType,
        inlineResponseName(op),
        op.returnDescription ?? op.summary
      );
    }
  }
  cb.line("defmodule ArchAstro.Auth do");
  cb.indent();
  cb.line('@moduledoc "Authentication operations generated from x-token-flows."');
  for (const op of spec.authOperations ?? []) {
    cb.line();
    emitAuthOperation(cb, op, spec.schemas);
  }
  cb.dedent();
  cb.line("end");
  return cb.toString();
}

type AuthFieldLocation = "path" | "query" | "body";

interface AuthInputEntry {
  field: FieldDef;
  originalName: string;
  wireName: string;
  location: AuthFieldLocation;
  collided: boolean;
}

function authInputEntries(op: OperationDef, schemas: ReadonlyArray<SchemaDef>): AuthInputEntry[] {
  const unionBody = authUnionBodySchema(op, schemas);
  const bodyFields = unionBody
    ? [{
      name: "body",
      required: true,
      sdkRole: "auth_union_body",
      type: { kind: "ref" as const, schema: unionBody.name },
    }]
    : authBodyFields(op, schemas).filter((field) => !field.sdkRole);
  const entries = [
    ...op.pathParams.map((field) => ({ field: { ...field }, location: "path" as const })),
    ...op.queryParams.map((field) => ({ field: { ...field }, location: "query" as const })),
    ...bodyFields.map((field) => ({ field: { ...field }, location: "body" as const })),
  ];
  const bases = entries.map(({ field }) => exFunctionName(field.name));
  const counts = new Map<string, number>();
  bases.forEach((base) => counts.set(base, (counts.get(base) ?? 0) + 1));
  const names = uniqueExFieldNames(entries.map(({ field, location }, index) =>
    (counts.get(bases[index]!) ?? 0) > 1 ? `${location}_${field.name}` : field.name
  ));

  return entries.map(({ field, location }, index) => ({
    field: { ...field, name: names[index]! },
    originalName: field.name,
    wireName: field.wireName ?? field.name,
    location,
    collided: (counts.get(bases[index]!) ?? 0) > 1,
  }));
}

function authUnionBodySchema(
  op: OperationDef,
  schemas: ReadonlyArray<SchemaDef>
): SchemaDef | undefined {
  if (!op.body?.schema || op.body.fields || op.body.schema === "inline") return undefined;
  const schema = schemas.find((candidate) => candidate.name === op.body!.schema);
  return schema?.unionType ? schema : undefined;
}

function authInputFields(op: OperationDef, schemas: ReadonlyArray<SchemaDef>): FieldDef[] {
  return authInputEntries(op, schemas).map((entry) => entry.field);
}

function authBodyFields(op: OperationDef, schemas: ReadonlyArray<SchemaDef>): FieldDef[] {
  if (op.body?.fields) return op.body.fields;
  if (op.body?.schema && op.body.schema !== "inline") {
    return schemas.find((schema) => schema.name === op.body!.schema)?.fields ?? [];
  }
  return [];
}

function authInputName(op: OperationDef): string {
  return operationTypeRoot(op, "AuthInput");
}

function elixirAuthMethodName(op: OperationDef): string {
  if (op.sdkName) return exFunctionName(op.sdkName);
  const segments = op.path.split("/").filter(Boolean);
  const lastSegment = segments.at(-1) ?? op.name;
  const name = exFunctionName(lastSegment);
  const paramNames = new Set(op.queryParams.map((param) => exFunctionName(param.name)));
  for (const field of op.body?.fields ?? []) {
    if (!field.sdkRole) paramNames.add(exFunctionName(field.name));
  }
  return paramNames.has(name) && segments.length >= 2
    ? exFunctionName(`${segments.at(-2)!}_${lastSegment}`)
    : name;
}

function authWireNames(op: OperationDef, schemas: ReadonlyArray<SchemaDef>): Map<string, string> {
  return new Map(authInputEntries(op, schemas).map((entry) => [
    entry.field.name,
    entry.collided ? `${entry.location}:${entry.wireName}` : entry.wireName,
  ]));
}

function emitAuthOperation(
  cb: CodeBuilder,
  op: OperationDef,
  schemas: ReadonlyArray<SchemaDef>
): void {
  const name = exFunctionName(op.sdkName ?? op.name);
  const entries = authInputEntries(op, schemas);
  const fields = entries.map((entry) => entry.field);
  const args = ["client"];
  const specs = ["ArchAstro.Client.t()"];
  if (fields.length > 0) {
    args.push("input");
    specs.push(`${typeModule(authInputName(op))}.t()`);
  }
  cb.line(`@doc ${heredoc([op.summary, op.description].filter(Boolean).join("\n\n") || `${op.method} ${op.path}`)}`);
  cb.line(`@spec ${name}(${specs.join(", ")}) :: ${operationResultSpec(op)}`);
  cb.line(`def ${name}(${args.join(", ")}) do`);
  cb.indent();
  cb.line(`path = ${authPathExpression(op, schemas)}`);
  const options: string[] = [];
  if (op.queryParams.length > 0) {
    cb.line("query =");
    cb.indent();
    cb.line("%{}");
    entries.filter((entry) => entry.location === "query").forEach((entry) => {
      cb.line(`|> ArchAstro.Codec.put_optional(${exString(entry.wireName)}, input.${exFieldName(entry.field.name)})`);
    });
    cb.dedent();
    options.push("query: query");
  }
  if (op.body) {
    const unionBody = entries.find((entry) => entry.field.sdkRole === "auth_union_body");
    if (unionBody) {
      cb.line(`body = input.${exFieldName(unionBody.field.name)}`);
    } else {
      cb.line("body =");
      cb.indent();
      cb.line("%{}");
      entries.filter((entry) => entry.location === "body").forEach((entry) => {
        cb.line(`|> ArchAstro.Codec.put_optional(${exString(entry.wireName)}, input.${exFieldName(entry.field.name)})`);
      });
      cb.dedent();
    }
    options.push("body: body");
  }
  if (op.rawResponse) options.push("raw: true");
  else options.push(`decode: ${operationDescriptor(op)}`);
  cb.line(`ArchAstro.HTTP.request(client, :${op.method.toLowerCase()}, path, [${options.join(", ")}])`);
  cb.dedent();
  cb.line("end");
}

function authPathExpression(op: OperationDef, schemas: ReadonlyArray<SchemaDef>): string {
  const entries = authInputEntries(op, schemas);
  const replacements: Array<{ patterns: string[]; expression: string }> = [];
  for (const param of op.pathParams) {
    const entry = entries.find((candidate) =>
      candidate.location === "path" && candidate.originalName === param.name
    )!;
    const local = `input.${exFieldName(entry.field.name)}`;
    replacements.push({
      patterns: [...new Set([`{${param.wireName ?? param.name}}`, `{${param.name}}`])],
      expression: `ArchAstro.Path.encode(${local})`,
    });
  }
  return interpolatedString(op.path, replacements);
}

function emitClient(spec: SdkSpec): string {
  const cb = new CodeBuilder("  ");
  beginFile(cb);
  cb.line("defmodule ArchAstro.GeneratedClient do");
  cb.indent();
  cb.line('@moduledoc false');
  cb.line(`@default_base_url ${exString(spec.baseUrl)}`);
  cb.line("@spec default_base_url() :: String.t()");
  cb.line("def default_base_url, do: @default_base_url");
  cb.dedent();
  cb.line("end");
  return cb.toString();
}

function channelTypeRoot(channel: ChannelDef, event: string, suffix: string): string {
  const facade = channel.sdkName ?? channel.className.replace(/Channel$/, "");
  return `ChannelPayloads.${pascalCase(`${facade}Channel`)}.${pascalCase(event)}.${suffix}`;
}

function joinPayloadName(channel: ChannelDef, joinDef: ChannelJoinDef, index: number): string {
  return channelTypeRoot(channel, joinDef.sdkTypeName ?? joinDef.name ?? `join_${index + 1}`, "Params");
}

function messageInputName(channel: ChannelDef, message: ChannelMessageDef): string {
  return channelTypeRoot(channel, message.sdkTypeName ?? message.event, "Input");
}

function messageResponseName(channel: ChannelDef, message: ChannelMessageDef): string {
  return channelTypeRoot(channel, message.sdkTypeName ?? message.event, "Response");
}

function pushPayloadName(channel: ChannelDef, push: ChannelPushDef): string {
  return channelTypeRoot(channel, push.sdkTypeName ?? push.event, "Payload");
}

function joinResponseName(channel: ChannelDef, joinDef: ChannelJoinDef, index: number): string {
  return channelTypeRoot(channel, joinDef.sdkTypeName ?? joinDef.name ?? `join_${index + 1}`, "Response");
}

function emitChannel(channel: ChannelDef): string {
  const cb = new CodeBuilder("  ");
  beginFile(cb);
  channel.joins.forEach((joinDef, index) => {
    const topicParams = topicParamNames(joinDef.topicPattern);
    const payload = joinDef.params.filter(
      (param) => !topicParams.some((placeholder) => matchesTopicParam(param, placeholder))
    );
    if (payload.length > 0) {
      emitInlineStructs(
        cb,
        joinPayloadName(channel, joinDef, index),
        queryLikeFields(payload),
        joinDef.description,
        paramWireNames(payload)
      );
    }
    if (joinDef.returnType.kind === "object" && joinDef.returnType.fields.length > 0) {
      emitInlineStructs(cb, joinResponseName(channel, joinDef, index), joinDef.returnType.fields, joinDef.description);
    } else {
      joinDef.returnType = emitNestedTypeStructs(
        cb,
        joinDef.returnType,
        joinResponseName(channel, joinDef, index),
        joinDef.description
      );
    }
  });
  for (const message of channel.messages) {
    if (message.params.length > 0) {
      emitInlineStructs(
        cb,
        messageInputName(channel, message),
        queryLikeFields(message.params),
        message.description,
        paramWireNames(message.params)
      );
    }
    if (message.returnType.kind === "object" && message.returnType.fields.length > 0) {
      emitInlineStructs(cb, messageResponseName(channel, message), message.returnType.fields, message.description);
    } else {
      message.returnType = emitNestedTypeStructs(
        cb,
        message.returnType,
        messageResponseName(channel, message),
        message.description
      );
    }
  }
  for (const push of channel.pushes) {
    if (push.payloadType.kind === "object" && push.payloadType.fields.length > 0) {
      emitInlineStructs(cb, pushPayloadName(channel, push), push.payloadType.fields, push.description);
    } else {
      push.payloadType = emitNestedTypeStructs(
        cb,
        push.payloadType,
        pushPayloadName(channel, push),
        push.description
      );
    }
  }

  const moduleName = `ArchAstro.Channels.${exModuleSegment(channel.sdkName ?? channel.className.replace(/Channel$/, ""))}`;
  cb.line(`defmodule ${moduleName} do`);
  cb.indent();
  cb.line(`@moduledoc ${heredoc(channel.description ?? `${channel.name} Phoenix channel.`)}`);
  const memberNames = uniqueExFunctionNames(
    [
      ...channel.joins.map((joinDef, index) => joinDef.name ?? (channel.joins.length > 1 ? `join_${index + 1}` : "join")),
      ...channel.messages.map((message) => message.event),
      ...channel.pushes.map((push) => `subscribe_${push.event}`),
    ],
    ["leave"]
  );
  channel.joins.forEach((joinDef, index) =>
    emitChannelJoin(cb, channel, joinDef, index, moduleName, memberNames[index]!)
  );
  channel.messages.forEach((message, index) =>
    emitChannelMessage(cb, channel, message, memberNames[channel.joins.length + index]!)
  );
  channel.pushes.forEach((push, index) =>
    emitChannelPush(
      cb,
      channel,
      push,
      memberNames[channel.joins.length + channel.messages.length + index]!
    )
  );
  cb.line();
  cb.line("@spec leave(ArchAstro.Channel.t()) :: :ok | {:error, ArchAstro.Error.reason()}");
  cb.line("def leave(channel), do: ArchAstro.Channel.leave(channel)");
  cb.dedent();
  cb.line("end");
  return cb.toString();
}

function queryLikeFields(params: ParamDef[]): FieldDef[] {
  return params.map((param) => ({ ...param }));
}

function topicParamNames(pattern: string): string[] {
  return [...new Set([...pattern.matchAll(/\{([^}]+)\}/g)].map((m) => m[1]!))];
}

function matchesTopicParam(param: ParamDef, placeholder: string): boolean {
  return param.name === placeholder || param.wireName === placeholder;
}

function emitChannelJoin(
  cb: CodeBuilder,
  channel: ChannelDef,
  joinDef: ChannelJoinDef,
  index: number,
  moduleName: string,
  name: string
): void {
  const topicParams = topicParamNames(joinDef.topicPattern);
  const payloadParams = joinDef.params.filter(
    (param) => !topicParams.some((placeholder) => matchesTopicParam(param, placeholder))
  );
  const topicLocals = uniqueExFunctionNames(topicParams, ["socket", "params", "topic"]);
  const args = ["socket", ...topicLocals];
  const specs = [
    "GenServer.server()",
    ...topicParams.map((name) => {
      const param = joinDef.params.find((candidate) => matchesTopicParam(candidate, name));
      return param ? typeSpec(param.type) : "String.t()";
    }),
  ];
  let payload = "%{}";
  if (payloadParams.length > 0) {
    const type = typeModule(joinPayloadName(channel, joinDef, index));
    payload = "params";
    args.push(payloadParams.some((param) => param.required) ? "params" : `params \\\\ %${type}{}`);
    specs.push(`${type}.t()`);
  }
  cb.line();
  cb.line(`@spec ${name}(${specs.join(", ")}) :: {:ok, ArchAstro.Channel.t()} | {:error, ArchAstro.Error.reason()}`);
  cb.line(`def ${name}(${args.join(", ")}) do`);
  cb.indent();
  const topic = interpolatedString(
    joinDef.topicPattern,
    topicParams.map((param, topicIndex) => ({
      patterns: [`{${param}}`],
      expression: topicLocals[topicIndex]!,
    }))
  );
  cb.line(`topic = ${topic}`);
  cb.line(`ArchAstro.Channel.join(socket, topic, ${payload}, ${moduleName}, ${channelTypeDescriptor(joinDef.returnType, joinResponseName(channel, joinDef, index))})`);
  cb.dedent();
  cb.line("end");
}

function emitChannelMessage(
  cb: CodeBuilder,
  channel: ChannelDef,
  message: ChannelMessageDef,
  name: string
): void {
  const args = ["channel"];
  const specs = ["ArchAstro.Channel.t()"];
  let payload = "%{}";
  if (message.params.length > 0) {
    const type = typeModule(messageInputName(channel, message));
    args.push(message.params.some((param) => param.required) ? "payload" : `payload \\\\ %${type}{}`);
    specs.push(`${type}.t()`);
    payload = "payload";
  }
  args.push("timeout \\\\ 5_000");
  specs.push("timeout()");
  const responseType = channelTypeSpec(message.returnType, messageResponseName(channel, message));
  cb.line();
  cb.line(`@spec ${name}(${specs.join(", ")}) :: {:ok, ${responseType}} | {:error, ArchAstro.Error.reason()}`);
  cb.line(`def ${name}(${args.join(", ")}) do`);
  cb.indent();
  cb.line(`ArchAstro.Channel.push(channel, ${exString(message.event)}, ${payload}, ${channelTypeDescriptor(message.returnType, messageResponseName(channel, message))}, timeout)`);
  cb.dedent();
  cb.line("end");
}

function emitChannelPush(
  cb: CodeBuilder,
  channel: ChannelDef,
  push: ChannelPushDef,
  name: string
): void {
  cb.line();
  cb.line(`@spec ${name}(ArchAstro.Channel.t(), pid()) :: :ok`);
  cb.line(`def ${name}(channel, subscriber \\\\ self()) do`);
  cb.indent();
  cb.line(`ArchAstro.Channel.subscribe(channel, ${exString(push.event)}, subscriber, ${channelTypeDescriptor(push.payloadType, pushPayloadName(channel, push))})`);
  cb.dedent();
  cb.line("end");
}

function channelTypeSpec(type: TypeRef, inlineName: string): string {
  if (type.kind === "object" && type.fields.length > 0) return `${typeModule(inlineName)}.t()`;
  if (type.kind === "object") return "ArchAstro.JSON.object() | :ok";
  return typeSpec(type);
}

function channelTypeDescriptor(type: TypeRef, inlineName: string): string {
  return type.kind === "object" && type.fields.length > 0 ? `{:ref, ${typeModule(inlineName)}}` : descriptor(type);
}

function typeSpec(type: TypeRef): string {
  switch (type.kind) {
    case "primitive":
      return type.type === "string" ? "String.t()" : type.type === "integer" ? "integer()" :
        type.type === "float" ? "number()" : type.type === "boolean" ? "boolean()" : "DateTime.t()";
    case "array": return `[${typeSpec(type.items)}]`;
    case "object": return type.fields.length === 0 ? "ArchAstro.JSON.object()" : objectMapSpec(type.fields);
    case "ref": return `${typeModule(type.schema)}.t()`;
    // Elixir typespecs do not support singleton binary literals. Keep the
    // wire representation honest instead of claiming these decode as atoms.
    case "enum": return "String.t()";
    case "union": return type.variants.map(typeSpec).join(" | ") || "ArchAstro.JSON.t()";
    case "nullable": return `${typeSpec(type.inner)} | nil`;
    case "optional": return typeSpec(type.inner);
    case "map": return `%{optional(${typeSpec(type.keyType)}) => ${typeSpec(type.valueType)}}`;
    case "void": return ":ok";
    case "unknown": return "ArchAstro.JSON.t()";
  }
}

function objectMapSpec(fields: ReadonlyArray<FieldDef>): string {
  const values = [...new Set(fields.map((field) => typeSpec(field.type)))];
  return `%{optional(String.t()) => ${values.join(" | ") || "ArchAstro.JSON.t()"}}`;
}

function descriptor(type: TypeRef): string {
  switch (type.kind) {
    case "primitive": return `:${type.type}`;
    case "array": return `{:list, ${descriptor(type.items)}}`;
    case "object": return `{:object, ${fieldDescriptors(type.fields)}}`;
    case "ref": return `{:ref, ${typeModule(type.schema)}}`;
    case "enum": return `{:enum, ${inspectList(type.values)}}`;
    case "union": {
      const variants = `[${type.variants.map(descriptor).join(", ")}]`;
      if (type.discriminator) {
      const inferredMapping = Object.fromEntries(
        type.variants
          .filter((variant): variant is Extract<TypeRef, { kind: "ref" }> => variant.kind === "ref")
          .map((variant) => [variant.schema, variant.schema])
      );
      const mapping = Object.entries(type.discriminator.mapping ?? inferredMapping)
          .map(([tag, schema]) => `${exString(tag)} => ${typeModule(schema)}`).join(", ");
        return `{:union, ${variants}, {${exString(type.discriminator.propertyName)}, %{${mapping}}}}`;
      }
      return `{:union, ${variants}}`;
    }
    case "nullable": return `{:nullable, ${descriptor(type.inner)}}`;
    case "optional": return `{:optional, ${descriptor(type.inner)}}`;
    case "map": return `{:map, ${descriptor(type.valueType)}}`;
    case "void": return ":void";
    case "unknown": return ":unknown";
  }
}

function fieldDescriptors(fields: ReadonlyArray<FieldDef>): string {
  return `[${fields.map((field) => `{${exString(field.name)}, ${fieldDescriptor(field)}}`).join(", ")}]`;
}

function fieldDescriptor(field: FieldDef): string {
  const value = descriptor(field.type);
  return field.required || field.type.kind === "optional" ? value : `{:optional, ${value}}`;
}

function inspectList(values: string[]): string {
  return `[${values.map(exString).join(", ")}]`;
}

function heredoc(value: string): string {
  const clean = value
    .replace(/\\/g, "\\\\")
    .replace(/"""/g, '\\"\\"\\"')
    .replace(/#\{/g, "\\#{")
    .trim();
  return `"""\n${clean}\n"""`;
}

function interpolatedString(
  value: string,
  replacements: ReadonlyArray<{ patterns: string[]; expression: string }>
): string {
  let template = value;
  const tokens: string[] = [];
  replacements.forEach((replacement, index) => {
    let token = `__ARCHASTRO_INTERPOLATION_${index}__`;
    while (template.includes(token)) token = `_${token}`;
    for (const pattern of replacement.patterns) template = template.split(pattern).join(token);
    tokens.push(token);
  });
  let literal = exString(template);
  replacements.forEach((replacement, index) => {
    literal = literal.split(tokens[index]!).join(`#{${replacement.expression}}`);
  });
  return literal;
}

export { exFunctionName, exModuleSegment } from "./identifiers.js";
