import { join } from "node:path";
import type { OperationDef, ResourceDef, SdkSpec, TypeRef, VersionedResourceSet } from "../../ast/types.js";
import { CodeBuilder } from "../../utils/codegen.js";
import { pascalCase } from "../../utils/naming.js";
import {
  exFunctionName,
  exModuleSegment,
  elixirResourceChain,
  inlineBodyName,
  prepareElixirSpec,
  queryParamsName,
  typeModule,
} from "../elixir/index.js";
import {
  exString,
  uniqueExFieldNames,
  uniqueExFileStems,
  uniqueExFunctionNames,
} from "../elixir/identifiers.js";
import { generateDummyValue, resolveBodyFields } from "./value-generator.js";
import { hoistInlineObjects } from "../python/inline-object-hoist.js";

export const ELIXIR_TESTS_DIR = "test/contract";
type GeneratedFiles = Record<string, string>;

const header = "# Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.\n" +
  "# This file is auto-generated by @archastro/sdk-generator. Do not edit.\n";

export function emitElixirContractTests(spec: SdkSpec, outDir: string): GeneratedFiles {
  spec = prepareElixirSpec(spec);
  const files: GeneratedFiles = {};
  const versionStems = uniqueExFileStems(spec.versions.map((version) => version.version));
  spec.versions.forEach((version, versionIndex) => {
    const resourceStems = uniqueExFileStems(version.resources.map((resource) => resource.name));
    version.resources.forEach((root, resourceIndex) => {
      const tests: TestCase[] = [];
      collectTests(spec, version, root, [root], tests);
      if (tests.length === 0) return;
      const path = join(
        outDir,
        ELIXIR_TESTS_DIR,
        versionStems[versionIndex]!,
        `${resourceStems[resourceIndex]!}_contract_test.exs`
      );
      files[path] = renderFile(version, root, tests, spec.schemas);
    });
  });
  const channelFileStems = uniqueExFileStems(spec.channels.map((channel) => channel.name));
  spec.channels.forEach((channel, index) => {
    const path = join(outDir, ELIXIR_TESTS_DIR, "channels", `${channelFileStems[index]!}_contract_test.exs`);
    files[path] = renderChannelFile(channel, spec.schemas);
  });
  return files;
}

function renderChannelFile(
  channel: SdkSpec["channels"][number],
  schemas: SdkSpec["schemas"]
): string {
  const cb = new CodeBuilder("  ");
  header.trimEnd().split("\n").forEach((line) => cb.line(line));
  cb.line();
  const contractName = channel.sdkName
    ? exModuleSegment(`${channel.sdkName}Channel`)
    : exModuleSegment(channel.className);
  cb.line(`defmodule ArchAstro.Contract.Channels.${contractName}Test do`);
  cb.indent();
  cb.line("use ExUnit.Case, async: false");
  cb.line("@moduletag :channel_contract");

  const facade = `ArchAstro.Channels.${exModuleSegment(channel.sdkName ?? channel.className.replace(/Channel$/, ""))}`;
  const memberNames = uniqueExFunctionNames(
    [
      ...channel.joins.map((joinDef, index) =>
        joinDef.name ?? (channel.joins.length > 1 ? `join_${index + 1}` : "join")
      ),
      ...channel.messages.map((message) => message.event),
      ...channel.pushes.map((push) => `subscribe_${push.event}`),
    ],
    ["leave"]
  );

  channel.joins.forEach((joinDef, joinIndex) => {
    const topicParams = [
      ...new Set([...joinDef.topicPattern.matchAll(/\{([^}]+)\}/g)].map((match) => match[1]!)),
    ];
    const payloadParams = joinDef.params.filter(
      (param) => !topicParams.some(
        (placeholder) => param.name === placeholder || param.wireName === placeholder
      )
    );
    const args = [
      "socket",
      ...topicParams.map((name) => {
        const param = joinDef.params.find(
          (candidate) => candidate.name === name || candidate.wireName === name
        );
        return param ? generateDummyValue(param.type, param.name, "elixir") : exString("test-value");
      }),
    ];
    if (payloadParams.length > 0) {
      args.push(structLiteral(
        channelPayloadModule(channel, joinDef.sdkTypeName ?? joinDef.name ?? `join_${joinIndex + 1}`, "Params"),
        payloadParams,
        schemas
      ));
    }

    cb.line();
    cb.line(`test ${exString(`${channel.name} ${joinDef.name ?? `join ${joinIndex + 1}`} facade matches the shared harness`)} do`);
    cb.indent();
    cb.line("assert :ok =");
    cb.indent();
    cb.line(`ArchAstro.ContractSupport.verify_channel(${exString(channel.name)}, ${exString(joinDef.topicPattern)}, fn socket, push ->`);
    cb.indent();
    const joinPattern = responsePattern(
      joinDef.returnType,
      channelPayloadModule(
        channel,
        joinDef.sdkTypeName ?? joinDef.name ?? `join_${joinIndex + 1}`,
        "Response"
      ),
      "%{}",
      schemas
    );
    cb.line(`assert {:ok, %ArchAstro.Channel{join_response: ${joinPattern}} = channel} = ${facade}.${memberNames[joinIndex]!}(${args.join(", ")})`);

    channel.messages.forEach((message, messageIndex) => {
      const messageArgs = ["channel"];
      if (message.params.length > 0) {
        messageArgs.push(structLiteral(
          channelPayloadModule(channel, message.sdkTypeName ?? message.event, "Input"),
          message.params,
          schemas
        ));
      }
      const messagePattern = responsePattern(
        message.returnType,
        channelPayloadModule(channel, message.sdkTypeName ?? message.event, "Response"),
        ":ok",
        schemas
      );
      cb.line(`assert {:ok, ${messagePattern}} = ${facade}.${memberNames[channel.joins.length + messageIndex]!}(${messageArgs.join(", ")})`);
    });
    channel.pushes.forEach((push, pushIndex) => {
      const name = memberNames[channel.joins.length + channel.messages.length + pushIndex]!;
      cb.line(`assert :ok = ${facade}.${name}(channel, self())`);
      cb.line(`assert :ok = push.(channel.topic, ${exString(push.event)})`);
      const payload = `push_payload_${pushIndex}`;
      cb.line(`assert_receive {:archastro_channel, ^channel, ${exString(push.event)}, ${payload}}`);
      const predicate = shapePredicate(
        push.payloadType,
        payload,
        channelPayloadModule(channel, push.sdkTypeName ?? push.event, "Payload"),
        schemas
      );
      if (predicate) cb.line(`assert ${predicate}`);
    });
    cb.line(`assert :ok = ${facade}.leave(channel)`);
    cb.line(":ok");
    cb.dedent();
    cb.line("end)");
    cb.dedent();
    cb.dedent();
    cb.line("end");
  });

  cb.dedent();
  cb.line("end");
  return cb.toString();
}

function channelPayloadModule(
  channel: SdkSpec["channels"][number],
  event: string,
  suffix: string
): string {
  const facade = channel.sdkName ?? channel.className.replace(/Channel$/, "");
  return typeModule(`ChannelPayloads.${pascalCase(`${facade}Channel`)}.${pascalCase(event)}.${suffix}`);
}

interface TestCase {
  moduleName: string;
  operationName: string;
  args: string[];
  label: string;
  errorStatuses: number[];
  streaming: boolean;
  successPattern: string;
  successAssertion?: string;
  streamRoute?: string;
  streamEvents?: Array<{ name: string; type: TypeRef; moduleName: string }>;
}

function collectTests(
  spec: SdkSpec,
  version: VersionedResourceSet,
  resource: ResourceDef,
  ancestry: ResourceDef[],
  output: TestCase[]
): void {
  const chain = elixirResourceChain(version, ancestry);
  const moduleName = ["ArchAstro", exModuleSegment(version.sdkName ?? version.version), ...chain.map(exModuleSegment)].join(".");
  for (const op of resource.operations) {
    const args = ["client"];
    resource.scopeParams.forEach((p) => args.push(generateDummyValue(p.type, p.name, "elixir")));
    op.pathParams.forEach((p) => args.push(generateDummyValue(p.type, p.name, "elixir")));
    if (op.body) {
      const fields = resolveBodyFields(op.body, spec.schemas);
      const moduleName = op.body.fields
        ? typeModule(inlineBodyName(op))
        : typeModule(op.body.schema);
      const schema = spec.schemas.find((candidate) => candidate.name === op.body!.schema);
      args.push(
        schema?.unionType
          ? renderUnionInput(schema, spec.schemas)
          : structLiteral(moduleName, fields, spec.schemas)
      );
    }
    if (op.queryParams.length > 0) {
      args.push(structLiteral(typeModule(queryParamsName(op)), op.queryParams, spec.schemas));
    }
    output.push({
      moduleName,
      operationName: exFunctionName(op.sdkName ?? op.name),
      args,
      label: `${op.method} ${op.path}`,
      errorStatuses: [...new Set(op.errors.map((error) => error.status))],
      streaming: Boolean(op.streaming),
      successPattern: operationSuccessPattern(op, spec.schemas),
      successAssertion: operationSuccessAssertion(
        op.returnType,
        typeModule(`Operations.${pascalCase(op.operationId)}.Response`),
        spec.schemas,
        operationSuccessPattern(op, spec.schemas)
      ),
      streamRoute: op.streaming ? `${op.method.toUpperCase()} ${op.path}` : undefined,
      streamEvents: op.streaming?.events.map((event) => ({
        name: event.event,
        type: event.dataType,
        moduleName: typeModule(
          `Operations.${pascalCase(op.operationId)}.StreamEvents.${event.sdkTypeName ?? pascalCase(event.event)}Data`
        ),
      })),
    });
  }
  resource.children.forEach((child) => collectTests(spec, version, child, [...ancestry, child], output));
}

function renderUnionInput(
  schema: SdkSpec["schemas"][number],
  schemas: SdkSpec["schemas"]
): string {
  const hoist = hoistInlineObjects(
    [{ name: "variant", type: schema.unionType!, required: true }],
    `${schema.name}.Nested.`,
    "typeddict",
    { hoistUnions: true }
  );
  const hoisted = new Map(hoist.hoisted.map((group) => [group.name, group.fields]));
  return renderInputValue(hoist.fields[0]!.type, schema.name, schemas, hoisted, new Set());
}

function structLiteral(
  moduleName: string,
  fields: ReadonlyArray<{ name: string; type: TypeRef; required: boolean }>,
  schemas: SdkSpec["schemas"]
): string {
  const rootName = moduleName.replace(/^ArchAstro\.Types\./, "");
  const hoist = hoistInlineObjects(fields, `${rootName}.Nested.`, "typeddict", {
    hoistUnions: true,
  });
  const hoisted = new Map(hoist.hoisted.map((group) => [group.name, group.fields]));
  return renderStruct(moduleName, hoist.fields, schemas, hoisted, new Set());
}

function renderStruct(
  moduleName: string,
  fields: ReadonlyArray<{ name: string; type: TypeRef; required: boolean }>,
  schemas: SdkSpec["schemas"],
  hoisted: ReadonlyMap<string, ReadonlyArray<import("../../ast/types.js").FieldDef>>,
  seen: Set<string>
): string {
  if (seen.has(moduleName)) return `struct(${moduleName})`;
  const nextSeen = new Set(seen).add(moduleName);
  const entries = fields
    .map((field, index) => ({ field, name: uniqueExFieldNames(fields.map((item) => item.name))[index]! }))
    .filter(({ field }) => field.required)
    .map(({ field, name }) =>
      `${name}: ${renderInputValue(field.type, field.name, schemas, hoisted, nextSeen)}`
    );
  return `%${moduleName}{${entries.join(", ")}}`;
}

function renderInputValue(
  type: TypeRef,
  fieldName: string,
  schemas: SdkSpec["schemas"],
  hoisted: ReadonlyMap<string, ReadonlyArray<import("../../ast/types.js").FieldDef>>,
  seen: Set<string>
): string {
  switch (type.kind) {
    case "ref": {
      const fields = hoisted.get(type.schema) ?? schemas.find((schema) => schema.name === type.schema)?.fields;
      const union = schemas.find((schema) => schema.name === type.schema)?.unionType;
      if (union) return renderInputValue(union, fieldName, schemas, hoisted, seen);
      return fields
        ? renderStruct(typeModule(type.schema), fields, schemas, hoisted, seen)
        : `%${typeModule(type.schema)}{}`;
    }
    case "object":
      return type.fields.length > 0
        ? renderStruct(typeModule(`${fieldName}.Nested`), type.fields, schemas, hoisted, seen)
        : "%{}";
    case "array":
      return "[]";
    case "union":
      return type.variants.length > 0
        ? renderInputValue(preferredInputVariant(type.variants), fieldName, schemas, hoisted, seen)
        : "nil";
    case "nullable":
    case "optional":
      return "nil";
    case "map":
    case "unknown":
      return "%{}";
    default:
      return generateDummyValue(type, fieldName, "elixir");
  }
}

function preferredInputVariant(variants: TypeRef[]): TypeRef {
  return variants.find((variant) => variant.kind === "nullable" || variant.kind === "optional")
    ?? variants.find((variant) => variant.kind === "array")
    ?? variants.find((variant) => variant.kind !== "ref" && variant.kind !== "object")
    ?? variants[0]!;
}

function renderFile(
  version: VersionedResourceSet,
  root: ResourceDef,
  tests: TestCase[],
  schemas: SdkSpec["schemas"]
): string {
  const cb = new CodeBuilder("  ");
  header.trimEnd().split("\n").forEach((line) => cb.line(line));
  cb.line();
  cb.line(`defmodule ArchAstro.Contract.${exModuleSegment(version.sdkName ?? version.version)}.${exModuleSegment(root.name)}Test do`);
  cb.indent();
  cb.line("use ExUnit.Case, async: false");
  cb.line();
  cb.line("setup do");
  cb.indent();
  cb.line("{:ok, client: ArchAstro.ContractSupport.client()}");
  cb.dedent();
  cb.line("end");
  for (const test of tests) {
    cb.line();
    if (test.streaming) cb.line("@tag :channel_contract");
    cb.line(`test ${exString(test.label)}, %{client: client} do`);
    cb.indent();
    if (test.streaming) {
      cb.line("_ = client");
      const expected = `[${(test.streamEvents ?? []).map((event) => exString(event.name)).join(", ")}]`;
      cb.line(`assert {:ok, events} = ArchAstro.ContractSupport.verify_stream(${exString(test.streamRoute!)}, ${expected}, fn client ->`);
      cb.indent();
      cb.line(`${test.moduleName}.${test.operationName}(${test.args.join(", ")})`);
      cb.dedent();
      cb.line("end)");
      (test.streamEvents ?? []).forEach((event, index) => {
        const data = `event_data_${index}`;
        cb.line(`assert %ArchAstro.SSE.Event{event: ${exString(event.name)}, data: ${data}} = Enum.at(events, ${index})`);
        const predicate = shapePredicate(event.type, data, event.moduleName, schemas);
        if (predicate) cb.line(`assert ${predicate}`);
      });
      cb.line(`assert :ok = ArchAstro.ContractSupport.verify_stream_error(${exString(test.streamRoute!)}, fn client ->`);
      cb.indent();
      cb.line(`${test.moduleName}.${test.operationName}(${test.args.join(", ")})`);
      cb.dedent();
      cb.line("end)");
    } else {
      cb.line(`assert {:ok, ${test.successPattern}} = ${test.moduleName}.${test.operationName}(${test.args.join(", ")})`);
      if (test.successAssertion) cb.line(test.successAssertion);
    }
    cb.dedent();
    cb.line("end");
    for (const status of test.streaming ? [] : test.errorStatuses) {
      cb.line();
      cb.line(`test ${exString(`${test.label} returns ${status}`)} do`);
      cb.indent();
      cb.line(`client = ArchAstro.ContractSupport.error_client(${status})`);
      const errorArgs = ["client", ...test.args.slice(1)];
      cb.line(`assert {:error, %ArchAstro.Error{status: ${status}}} = ${test.moduleName}.${test.operationName}(${errorArgs.join(", ")})`);
      cb.dedent();
      cb.line("end");
    }
  }
  cb.dedent();
  cb.line("end");
  return cb.toString();
}

function shapePredicate(
  type: TypeRef,
  variable: string,
  inlineObjectModule: string,
  schemas: SdkSpec["schemas"]
): string | undefined {
  switch (type.kind) {
    case "primitive":
      if (type.type === "integer") return `is_integer(${variable})`;
      if (type.type === "float") return `is_number(${variable})`;
      if (type.type === "boolean") return `is_boolean(${variable})`;
      if (type.type === "datetime") return `is_struct(${variable}, DateTime)`;
      return `is_binary(${variable})`;
    case "enum":
      return `${variable} in [${type.values.map(exString).join(", ")}]`;
    case "array":
      return `is_list(${variable})`;
    case "map":
      return `is_map(${variable})`;
    case "object":
      return type.fields.length > 0
        ? `is_struct(${variable}, ${inlineObjectModule})`
        : `is_map(${variable})`;
    case "ref": {
      const schema = schemas.find((candidate) => candidate.name === type.schema);
      if (schema?.unionType) {
        const hoist = hoistInlineObjects(
          [{ name: "variant", type: schema.unionType, required: true }],
          `${schema.name}.Nested.`,
          "typeddict",
          { hoistUnions: true }
        );
        return shapePredicate(hoist.fields[0]!.type, variable, inlineObjectModule, schemas);
      }
      return `is_struct(${variable}, ${typeModule(type.schema)})`;
    }
    case "nullable": {
      const inner = shapePredicate(type.inner, variable, inlineObjectModule, schemas);
      return inner ? `is_nil(${variable}) or ${inner}` : undefined;
    }
    case "optional":
      return shapePredicate(type.inner, variable, inlineObjectModule, schemas);
    case "union": {
      const rootName = inlineObjectModule.replace(/^ArchAstro\.Types\./, "");
      const hoist = hoistInlineObjects(
        [{ name: "value", type, required: true }],
        `${rootName}.Nested.`,
        "typeddict",
        { hoistUnions: true }
      );
      const resolved = hoist.fields[0]!.type;
      const variants = resolved.kind === "union" ? resolved.variants : [resolved];
      const predicates = variants
        .map((variant) => shapePredicate(variant, variable, inlineObjectModule, schemas))
        .filter((predicate): predicate is string => Boolean(predicate));
      return predicates.length > 0 ? `(${predicates.join(") or (")})` : undefined;
    }
    case "void":
      return `${variable} == :ok`;
    case "unknown":
      return undefined;
  }
}

function operationSuccessPattern(op: OperationDef, schemas: SdkSpec["schemas"]): string {
  if (op.rawResponse) return "%Req.Response{}";
  const inlineName = typeModule(`Operations.${pascalCase(op.operationId)}.Response`);
  const pattern = responsePattern(op.returnType, inlineName, "%{}", schemas);
  return pattern === "_value" ? "value" : pattern;
}

function responsePattern(
  type: TypeRef,
  inlineObjectModule?: string,
  emptyObjectPattern = "%{}",
  schemas: SdkSpec["schemas"] = []
): string {
  switch (type.kind) {
    case "ref": return schemas.some((schema) => schema.name === type.schema && schema.unionType)
      ? "_value"
      : `%${typeModule(type.schema)}{}`;
    case "object": return type.fields.length > 0 && inlineObjectModule
      ? `%${inlineObjectModule}{}`
      : emptyObjectPattern;
    case "array": return "items";
    case "map": return "%{}";
    case "void": return ":ok";
    case "nullable": return "value";
    case "optional": return responsePattern(type.inner, inlineObjectModule, emptyObjectPattern, schemas);
    default: return "_value";
  }
}

function operationSuccessAssertion(
  type: TypeRef,
  inlineObjectModule?: string,
  schemas: SdkSpec["schemas"] = [],
  successPattern?: string
): string | undefined {
  if (type.kind === "array") return "assert is_list(items)";
  if (type.kind === "optional") {
    return operationSuccessAssertion(type.inner, inlineObjectModule, schemas, successPattern);
  }
  if (successPattern === "value") {
    const predicate = shapePredicate(type, "value", inlineObjectModule!, schemas);
    return predicate ? `assert ${predicate}` : undefined;
  }
  return undefined;
}
